# Copyright 2017 AT&T Intellectual Property.  All other rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# In order to fix rate limit error
#
# 429 Too Many Requests - Server message: too many requests:
#   You have reached your pull rate limit.
#   You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ARG FROM=quay.io/airshipit/ubuntu:noble
FROM ${FROM}

LABEL org.opencontainers.image.authors='airship-discuss@lists.airshipit.org, irc://#airshipit@freenode' \
      org.opencontainers.image.url='https://airshipit.org' \
      org.opencontainers.image.documentation='https://airship-promenade.readthedocs.org' \
      org.opencontainers.image.source='https://opendev.org/airship/promenade' \
      org.opencontainers.image.vendor='The Airship Authors' \
      org.opencontainers.image.licenses='Apache-2.0'

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PORT=9000

EXPOSE $PORT

VOLUME /etc/promenade
VOLUME /target

RUN set -ex \
    && apt-get update -qq \
    && apt-get upgrade -y \
    && apt-get install --no-install-recommends -y \
        ca-certificates \
        curl \
        dnsutils \
        golang-cfssl \
        gpg \
        gpg-agent \
        libpcre3 \
        libpython3.12 \
        python3 \
        python3-setuptools \
        rsync \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/* \
        /usr/share/man \
        /usr/share/doc \
        /usr/share/doc-base

# Add promenade user
RUN (userdel -r ubuntu || true) 2>/dev/null \
      && (groupdel ubuntu || true) 2>/dev/null \
      && groupadd -g 1000 promenade \
      && useradd -u 1000 -g promenade -m -d /opt/promenade -s /bin/bash promenade

WORKDIR /opt/promenade

COPY --chown=promenade:promenade requirements-frozen.txt ./

RUN set -ex \
        && buildDeps=' \
        automake \
        gcc \
        libffi-dev \
        libpcre3-dev \
        libpq-dev \
        libssl-dev \
        libtool \
        libyaml-dev \
        make \
        pkg-config \
        python3-dev \
        python3-pip \
        ' \
        && apt-get -qq update \
        # Keep git separate so it's not removed below
        && apt-get install -y $buildDeps git --no-install-recommends \
        && python3 -m pip install -U pip --break-system-packages --ignore-installed \
        && pip3 install -r requirements-frozen.txt \
            --no-cache-dir --break-system-packages \
        && apt-get purge -y --auto-remove $buildDeps \
        && apt-get autoremove -yqq --purge \
        && apt-get clean \
        && rm -rf \
            /var/lib/apt/lists/* \
            /tmp/* \
            /var/tmp/* \
            /root/.cache \
            /usr/share/man \
            /usr/share/doc \
            /usr/share/doc-base

COPY --chown=promenade:promenade entrypoint.sh ./entrypoint.sh
COPY --chown=promenade:promenade . ./

RUN chmod 755 ./entrypoint.sh

# Setting promenade version for PBR
ENV PBR_VERSION=1.1.0

RUN pip3 install . --no-cache-dir --break-system-packages

ENTRYPOINT ["/opt/promenade/entrypoint.sh"]
CMD ["server"]

USER promenade
