{{/*
This manifest results a secret being created which has the key information
needed for backing up and restoring the etcd database.
*/}}

{{- if and .Values.backup.enabled .Values.manifests.secret_backup_restore }}

{{- $envAll := . }}
{{- $userClass := "backup_restore" }}
{{- $secretName := index $envAll.Values.secrets.etcd $userClass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  BACKUP_ENABLED: {{ $envAll.Values.backup.enabled | quote | b64enc }}
  BACKUP_BASE_PATH: {{ $envAll.Values.backup.host_backup_path | b64enc }}
  LOCAL_DAYS_TO_KEEP: {{ $envAll.Values.backup.no_backup_keep | quote | b64enc }}
  REMOTE_BACKUP_ENABLED: {{ $envAll.Values.backup.remote_backup.enabled | quote | b64enc }}
  REMOTE_BACKUP_CONTAINER: {{ $envAll.Values.backup.remote_backup.container_name | b64enc }}
  REMOTE_BACKUP_DAYS_TO_KEEP: {{ $envAll.Values.backup.remote_backup.days_to_keep | quote | b64enc }}
  REMOTE_BACKUP_STORAGE_POLICY: {{ $envAll.Values.backup.remote_backup.storage_policy | b64enc }}
  REMOTE_BACKUP_RETRIES: {{ $envAll.Values.backup.remote_backup.number_of_retries | quote | b64enc }}
  REMOTE_BACKUP_SEND_DELAY_MIN: {{ $envAll.Values.backup.remote_backup.delay_range.min | quote | b64enc }}
  REMOTE_BACKUP_SEND_DELAY_MAX: {{ $envAll.Values.backup.remote_backup.delay_range.max | quote | b64enc }}
  THROTTLE_BACKUPS_ENABLED: {{ $envAll.Values.backup.remote_backup.throttle_backups.enabled | quote | b64enc }}
  THROTTLE_LIMIT: {{ $envAll.Values.backup.remote_backup.throttle_backups.sessions_limit | quote | b64enc }}
  THROTTLE_LOCK_EXPIRE_AFTER: {{ $envAll.Values.backup.remote_backup.throttle_backups.lock_expire_after | quote | b64enc }}
  THROTTLE_RETRY_AFTER: {{ $envAll.Values.backup.remote_backup.throttle_backups.retry_after | quote | b64enc }}
  THROTTLE_CONTAINER_NAME: {{ $envAll.Values.backup.remote_backup.throttle_backups.container_name | quote | b64enc }}
...
{{- end }}
