---
apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    tier: control-plane
    component: kube-scheduler
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: {{ config['Versions']['images']['kubernetes']['scheduler'] }}
      command:
      - ./hyperkube
      - scheduler
      - --leader-elect=true
      - --kubeconfig=/etc/kubernetes/scheduler/kubeconfig.yaml
      - --v=5
      volumeMounts:
        - name: config
          mountPath: /etc/kubernetes/scheduler
  volumes:
    - name: config
      hostPath:
        path: /etc/kubernetes/scheduler
