apiVersion: v1
appVersion: v3.29.1
description: Tigera Operator for Calico
name: tigera-operator
version: 0.1.0
home: https://github.com/projectcalico/calico
sources:
  - https://github.com/projectcalico/calico
  - https://github.com/tigera/operator
maintainers:
  - name: Airship Authors
