{%- if 'kubeadm=enabled' in config.get_first('Genesis:labels.dynamic', 'KubernetesNode:labels.dynamic') %}---
apiVersion: kubeadm.k8s.io/v1beta4
caCertPath: /etc/kubernetes/pki/ca.crt
{%- if 'kubernetes-apiserver=enabled' in config.get_first('Genesis:labels.dynamic', 'KubernetesNode:labels.dynamic') %}
controlPlane:
  localAPIEndpoint:
    advertiseAddress: "{{ config['KubernetesNode:ip'] }}"
    bindPort: 6443
{%- endif %}
discovery:
  file:
    kubeConfigPath: /etc/kubernetes/admin.conf
kind: JoinConfiguration
nodeRegistration:
  imagePullPolicy: IfNotPresent
  imagePullSerial: false
  name: {{ config['KubernetesNode:hostname'] }}
  criSocket: "unix:///run/containerd/containerd.sock"
  ignorePreflightErrors:
    - FileAvailable--etc-kubernetes-kubelet.conf
    - Port-10250
  taints: []
skipPhases:
{%- if 'kubernetes-apiserver=enabled' in config.get_first('Genesis:labels.dynamic', 'KubernetesNode:labels.dynamic') %}
  - control-plane-prepare/download-certs
  - control-plane-prepare/certs
  - control-plane-prepare/kubeconfig
  - kubelet-start
  - control-plane-join
{%- else %}
  - control-plane-prepare
  - kubelet-start
  - control-plane-join
  - wait-control-plane
{%- endif %}
{%- endif %}
