# Copyright 2017 AT&T Intellectual Property.  All other rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

images:
  tags:
    dep_check: quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble
    anchor: quay.io/airshipit/kubeadm-utility:latest-ubuntu_noble
    haproxy: haproxy:1.8.25
    containerd_pause: docker-open-nc.zc1.somedomain.com/google_containers/pause-amd64:latest
  pull_policy: "IfNotPresent"
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

bootstrap:
  compress_fs: tar
  # it's more convenient to debug if it is true
  string_data: false
  # in case there is per-node data the next field can be used to generate only script for 1 node so
  # it is easier to extract. in that case only 1 secret will be generated with the name {{ include "kubeadm.fullname" $envAll }}-bootstrap
  # without suffix-<nodename>. Using this parameter disables producing other manifests generated in _main.tpl to help sed find the needed field only.
  # this is because we assume that bootstrap.nodename is used only for manual helm template execution
  # nodename: <some node>

anchor:
  period: 15
  labels:
    common:
      node_selector_key: kubeadm
      node_selector_value: enabled
    masters:
      node_selector_key: kubernetes-apiserver
      node_selector_value: enabled

etcd_service:
  name: kubernetes-etcd
  ip: "10.96.0.2"
  service_client:
    enable_node_port: false
    node_port: 32379
    port: 2379
    # TODO: must match with kubeadm.settings.etcd_servers ports
    target_port: 2379

haproxy:
  container_config_dir: /usr/local/etc/haproxy
  host_config_dir: /etc/kubernetes/kubeadm/addons
  period: 5
  conf_parts:
    global:
      - maxconn 10240
    defaults:
      - timeout connect 5000ms
      - timeout client 24h
      - timeout server 24h
    frontend:
      - mode tcp
    backend:
      - mode tcp
      - option tcp-check
      - option redispatch

# files:
#   rm_files: #groupname
#     - path: /usr/local/share/ca/certain/dosntexist
#       state: "rm"
#   files:
#     - path: /usr/local/share/ca/certain
#       state: "dir" # or touch
#       owner: "root:root" #optional
#       mode: "0600" #optional
#     - path: /usr/local/share/ca/certain2
#       state: "copy" #  or content or tpl
#       from: "/usr/local/share/ca/certain/filename"
#       owner: "root:root" #optional
#       mode: "0600" #optional

# we're storing all files to the 3 'flat' folders:
# "${nodes_dirs_dir}/allnodes" "${nodes_dirs_dir}/ctrlnodes" "${nodes_dirs_dir}/per-node"
# each folder may have several unique prefixes depending on which
# fs we're setting permissions. if there is no data, empty owner and mode are passed
# and setting of permissions is skept in that case.
# the approach with 3 folder allows to deliver files to nodes in a compact way wihtout duplication.
permissions:
  # certs/kubelet
  "/etc/kubernetes/pki":
    owner: "root:root"
    mode: "0700"
    prefixes:
      # produced by certs phase
      "pkipriv_": # keys
        owner: "root:root"
        mode: "0600"
      "pkipub_": # certs,
        owner: "root:root"
        mode: "0644"
      # produced by kubelet phase
      "kubeletpkipriv_": # keys
        owner: "root:root"
        mode: "0600"
      "kubeletpkipub_": # certs
        owner: "root:root"
        mode: "0644"
  "/etc/kubernetes/pki/etcd":
    owner: "root:root"
    mode: "0700"
    prefixes:
      "etcdpriv_": # keys
        owner: "root:root"
        mode: "0600"
      "etcdpub_": # certs,
        owner: "root:root"
        mode: "0600" #"0644"
  "/etc/default":
    owner: "root:root"
    mode: "0700"
    prefixes:
      "kubelet":
        owner: "root:root"
        mode: "0600"
  "/etc/systemd/system":
    owner: "root:root"
    mode: "0700"
    prefixes:
      "kubelet.service":
        owner: "root:root"
        mode: "0600"
      "kube-cgroup.service":
        owner: "root:root"
        mode: "0600"
  "/var/lib/kubelet":
    owner: "root:root"
    mode: "0700"
    prefixes:
      "config.yaml":
        owner: "root:root"
        mode: "0600"
  "/etc/kubernetes":
    owner: "root:root"
    prefixes:
      # produced by kubeconfig phase
      "admin.conf":
        owner: "root:root"
        mode: "0600"
      "controller-manager.conf":
        owner: "root:root"
        mode: "0600"
      "scheduler.conf":
        owner: "root:root"
        mode: "0600"
      # produced by kubelet phase
      "kubelet.conf":
        owner: "root:root"
        mode: "0600"
  "/etc/containerd":
    owner: "root:root"
    prefixes:
      "config.toml":
        owner: "root:root"
        mode: "0600"
  "/usr/local/sbin":
    owner: "root:root"
    prefixes:
      "kube-cgroup.sh":
        owner: "root:root"
        mode: "0600"
  "/etc/kubernetes/kubeadm":
    owner: "root:root"
    mode: "0700"
    prefixes:
      "kubeadm_":
        owner: "root:root"
        mode: "0600"
  "/etc/kubernetes/kubeadm/patches":
    owner: "root:root"
    mode: "0700"
    prefixes:
      kubeadmpatch_:
        owner: "root:root"
        mode: "0600"
  "/etc/kubernetes/apiserver":
    owner: "root:root"
    mode: "0700"
    prefixes:
      "kubeadmapiserver_":
        owner: "root:root"
        mode: "0600"
  "/etc/kubernetes/kubeadm/addons":
    owner: "root:root"
    mode: "0700"
  "/etc/kubernetes/manifests":
    prefixes:
      # produced by vip phase
      "manifests_":
        owner: "root:root"
        mode: "0600"


cluster_config: {}
  # if not specified - any in accordance to kubeadm version
  # kubernetesVersion: v1.36.3

kubeconfig:
  clusterName: kubernetes
  controlPlaneEndpoint: 127.0.0.1:6443

kubelet:
  restart: true

containerd:
  version: v3
  # auths:
  #   - repo: docker-open-nc.zc1.somedomain.com
  #     auth: user:password

# this is main data about cluster in full mode
# and potentially ca mode in case there is an
# additional haproxy static pod
# TODO: rename masters to control plance nodes everywhere, it's kubeadm terminology
# we may also don't need genesis. potenially we can bootstrap from any controller node
# they must be identical/interchangable in the end of the day
# ksn stands for k8s network
# control_plane:
#   genesis:
#     hostname: hostname0
#   masters:
#   - hostname: hostname0
#     ip:
#       ksn: 172.29.0.139
#   - hostname: hostname1
#     ip:
#       ksn: 172.29.0.144
#   - hostname: hostname2
#     ip:
#       ksn: 172.29.0.149
#   - hostname: hostname3
#     ip:
#       ksn: 172.29.0.154

# here is where all secrets are provided
# 3 options are supported:
# 1. no secrets - assuming that kubadm will be used to generate everything
# 2. ca key/crt are provided - kubeadm will be used to generate the rest
# 3. all secrets (including etcd) are pregenerated and kubeadm will be used only only for
#    certain phases like maintaining manifests
# NOTE: at the moment we don't support external etcd
# see templates/utils/_k8s_pki_val_extract.tpl for implementation details
# to use a different structure - override it in tpl section
certs:
  # expected structure:
  # perms:
  #   pki_dir:
  #     owner: "root:root"
  #     mode: "0700"
  #   pki_files:
  #     owner: "root:root"
  #     mode: "0600"
  #   etcd_dir: # inherit pki_dir if not defines
  #     owner: "root:root"
  #     mode: "0700"
  #   etcd_files: # inherit pki_files if not defines
  #     owner: "root:root"
  #     mode: "0600"

  # ca:
  #   crt: placeholder
  #   key: placeholder

  # sa:
  #   key: placeholder
  #   pub: placeholder
  # ...
  # see overrides/pki-*.yaml


# resources prefix
fullnameOverride: kubeadm-service

# manifests gates
# for day 1: bootstrap/bootstrap_joing will contain kubeadm init/join related step for node named genesis for init and
#            kubeadm join for the rest of the nodes. doesn're require anything else.
#            bootstrap scipt can be up to ~150Kb (in case of perNode is used), that's why the script separated onto
#            dedicated secret for each node, since Secrets have limit 1 - 2Mb and
#            we definetly will go beyond this limit in case of 10-20 nodes.
# for day 2: daemonset perform it bin/bin_helpers/fs_common/fs_masters_fs/fs_per_node/etc/rbac needed for daemonsets

manifests:
  configmap_bin: true
  configmap_for_kubeadm: true
  secret_daemonset_fs_common: true
  secret_daemonset_fs_masters: true
  secret_daemonset_fs_per_node: true
  secret_bootstrap: false
  daemonset_masters: true
  daemonset_workers: true
  etcd_service: false
  rbac: true

#### BUNDLE CONFIG #####
bundle:
  tpl: {}
    #"sometpl": "hello"
  # Mapping of the manifest to the templates. default is 'override'-templates type
  # those are equialent:
  #
  # <manifest-id>: "<path>"
  # <manifest-id>:
  #   - "override"
  #   - "<path>"
  #
  # Override tries to find if there is a template set in
  # .Values.manifests.tpl.<path>
  # and if found it uses that. if not it fallbacks to
  # to chart existing templates by path $dot.Chart.Name/<path>
  #
  # instead of override it is also possibe to use: tpl, fs and include
  # 1. "tpl" value forces to the template from .Values.manifests.tpl.<path>
  # 2. "fs" value forces to the template accessible by $dot.Chart.Name/<path>
  #    You can use either local chart temlate e.g. templates/<filename>
  #    Or even templates from dependencies e.g.  charts/<dep chart name>/templates/<filename>
  # 3. "include" value is the same as fs, but allows to use path without $dot.Chart.Name prefix
  #     that allows techincally to use and tempalte create with define.
  manifests:
    # ovrd_configmap_apiserver_misc: "templates/_configmap_apiserver_misc.yaml"
    # ovrd_configmap_bin: "templates/_configmap_bin.yaml"
    # ovrd_configmap_certs: "templates/_configmap_certs.yaml"
    # ovrd_configmap_etcd_certs: "templates/_configmap_etcd_certs.yaml"
    # ovrd_configmap_jobs: "templates/_configmap_jobs.yaml"
    # ovrd_configmap_kubeadm: "templates/_configmap_kubeadm.yaml"
    # ovrd_configmap_kubeconfig: "templates/_configmap_kubeconfig.yaml"
    # ovrd_configmap_kubelet: "templates/_configmap_kubelet.yaml"
    # ovrd_configmap_patches: "templates/_configmap_patches.yaml"
    # ovrd_daemonset_masters: "templates/_daemonset_masters.yaml"
    # ovrd_daemonset_workers: "templates/_daemonset_workers.yaml"
    # ovrd_etcd_service: "templates/_etcd_service.yaml"
    # ovrd_rbac: "templates/_rbac.yaml"
# here you can defind overrides for files
#  tpl:
#    <path>: |
#      <template>
# here is a flag which will print some extra comments
#  debug: true

# this is a re-configurable default template - entrypoint of the chart
entrypoint:
  "default": |
    {{ tuple . "templates/phases/_main.tpl" | include "kubeadm.bundle.template" }}
    {{ include "kubeadm.bundle.manifests" . }}

