{{/*
Copyright 2026 AT&T Intellectual Property.  All other rights reserved.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
   http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{/* Note: this file is called from templates/phases/_main.tpl and k8sConfDict contains lots of cached info */}}
{{- $envAll := index . 0 -}}
{{- $k8sConfDict := index . 1 -}}

{{- if or ($envAll.Values.manifests.secret_daemonset_fs_common) ($envAll.Values.manifests.secret_daemonset_fs_masters) ($envAll.Values.manifests.secret_daemonset_fs_per_node) }}

{{- if $envAll.Values.manifests.secret_daemonset_fs_common -}}
{{- $allNodes := get $k8sConfDict "allNodes" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeadm.fullname" $envAll }}-fs-allnodes
type: Opaque
{{- if eq (len $allNodes) 0 }}
data: {}
{{- else }}
stringData:
{{- range $k,$v := $allNodes }}
  {{ $k }}: |
{{ get $v "content" | indent 4 -}}
{{ end -}}
{{ end -}}
{{ end -}}

{{- if $envAll.Values.manifests.secret_daemonset_fs_masters -}}
{{- $controlPlaneNodes := get $k8sConfDict "controlPlaneNodes"}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeadm.fullname" $envAll }}-fs-ctrlnodes
type: Opaque
{{- if eq (len $controlPlaneNodes) 0 }}
data: {}
{{- else }}
stringData:
{{- range $k,$v := $controlPlaneNodes }}
  {{ $k }}: |
{{ get $v "content" | indent 4 -}}
{{ end -}}
{{ end -}}
{{ end -}}


{{- if and ($envAll.Values.manifests.secret_daemonset_fs_per_node) (hasKey $k8sConfDict "perNode") -}}
{{- $perNode := get $k8sConfDict "perNode" -}}

{{/*
  right now for 20 nodes I'm getting 150b -
  it means this will work for ~100nodes+.

  TODO:
  if we want more, the first option is to split secrets per file type:
  separate secret for kubelet cert, separate for kubelet key
  separate for etcd pki (that will be enough, because it is only for cntrollers)
  this should increase the limit at least to 200-300nodes.

  if we need even more -  we'll need to introduce some groups for nodes and separate them via labels
  in order for daemonset to handle that properly. OR even better - we can use kubectl to download
  the a dedicated secret/secrets to the node and in thie secret we can just reference the target.
  that allows basically to share a lot.
*/}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeadm.fullname" $envAll }}-fs-pernode
type: Opaque
data:
{{ range $nodeName,$nodeFs := $perNode }}
  {{- $fs := dict -}}
  {{- range $k,$v := $nodeFs }}
    {{- $_ := set $fs (print "per-node/" $k) $v -}}
  {{- end }}
  {{ $nodeName }}.tar: {{ $fs | include "tar" | b64enc | indent 2 }}
{{ end -}}

{{- end -}}

{{- end }}