# in order to switch to vip in declarative way we just need to change:
kubeconfig:
  controlPlaneEndpoint: 127.0.0.1:6553
  # for scheduler and controller manager
  controlPlaneLocalEndpoint: 127.0.0.1:6443

# and configure vip (need to know ips of CP)
vip:
  # it's a tpl string - can use include and etc, and also can produse "*:6553|${NODE_IP}:6443" for heredoc
  init: "*:6553|172.29.0.139:6443,172.29.0.144:6443,172.29.0.149:6443,172.29.0.154:6443"