---
pod:
  labels:
    etcd-backup:
      staggered-backups: enabled
  affinity:
    etcd_backup:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: status.phase
                  operator: NotIn
                  values:
                    - Running
                - key: staggered-backups
                  operator: In
                  values:
                    - enabled
            namespaces:
              - openstack
              - kube-system
              - osh-infra
            topologyKey: kubernetes.io/os
...
